<?php
session_start();
require_once '../php/db_connect.php';

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    http_response_code(401);
    echo "Not authorized";
    exit();
}

// Check if plan ID is provided
if (!isset($_GET['id']) || !is_numeric($_GET['id'])) {
    http_response_code(400);
    echo "Invalid meal plan ID";
    exit();
}

$plan_id = (int)$_GET['id'];
$user_id = $_SESSION['user_id'];

// Get the requested meal plan and verify ownership
$plan_sql = "SELECT * FROM meal_plans WHERE id = $plan_id AND user_id = $user_id";
$plan_result = $conn->query($plan_sql);

if ($plan_result->num_rows == 0) {
    http_response_code(404);
    echo "Meal plan not found or you don't have permission to download it";
    exit();
}

$plan = $plan_result->fetch_assoc();
$plan_data = json_decode($plan['plan_data'], true);

// We'll use TCPDF library for PDF generation
// For this example, we'll simulate PDF generation with HTML content

// Set the content type for PDF download
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="' . $plan['plan_name'] . '.pdf"');

// Include the TCPDF library (you would need to install this)
// require_once '../vendor/tcpdf/tcpdf.php';

// Since we don't have TCPDF installed, we'll generate a simple HTML file
// and force download it instead for this example
header('Content-Type: text/html');

// Get day names
$day_names = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
$num_days = count($plan_data);

// Start generating HTML content
$html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>' . htmlspecialchars($plan['plan_name']) . '</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
        h1 { text-align: center; color: #4CAF50; }
        .day { margin-bottom: 30px; }
        .day-title { background-color: #f1f8e9; padding: 10px; border-radius: 5px; }
        .meals { display: flex; flex-wrap: wrap; }
        .meal { width: 300px; margin: 10px; border: 1px solid #ddd; border-radius: 5px; overflow: hidden; }
        .meal-title { background-color: #f8f8f8; padding: 10px; margin: 0; }
        .meal-content { padding: 10px; }
        .meal-info { display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 10px; }
        .meal-info span { background-color: #f5f5f5; padding: 3px 8px; border-radius: 15px; font-size: 13px; }
    </style>
</head>
<body>
    <h1>' . htmlspecialchars($plan['plan_name']) . '</h1>';

// Add days
for ($day_index = 0; $day_index < $num_days; $day_index++) {
    $day_data = $plan_data[$day_index];
    $day_name = isset($day_names[$day_index]) ? $day_names[$day_index] : 'Day ' . ($day_index + 1);
    
    $html .= '<div class="day">
        <h2 class="day-title">' . $day_name . ' - ' . $day_data['totals']['calories'] . ' calories</h2>
        <div class="meals">';
    
    // Add meals for the day
    foreach ($day_data['meals'] as $meal_index => $meal) {
        $meal_names = ['Breakfast', 'Lunch', 'Dinner', 'Snack 1', 'Snack 2', 'Snack 3'];
        $meal_name = isset($meal_names[$meal_index]) ? $meal_names[$meal_index] : 'Meal ' . ($meal_index + 1);
        
        $html .= '<div class="meal">
            <h3 class="meal-title">' . $meal_name . '</h3>
            <div class="meal-content">
                <h4>' . htmlspecialchars($meal['name']) . '</h4>
                <div class="meal-info">
                    <span>' . ($meal['prep_time'] + $meal['cook_time']) . ' mins</span>
                    <span>' . $meal['calories'] . ' cal</span>
                    <span>' . $meal['protein'] . 'g protein</span>
                    <span>' . $meal['carbs'] . 'g carbs</span>
                    <span>' . $meal['fat'] . 'g fat</span>
                </div>
                <p>' . (isset($meal['description']) ? htmlspecialchars($meal['description']) : 'No description available.') . '</p>
            </div>
        </div>';
    }
    
    $html .= '</div></div>';
}

$html .= '<div style="text-align: center; margin-top: 30px; color: #888; font-size: 12px;">
        Generated by MealPlanner on ' . date('F j, Y') . '
    </div>
</body>
</html>';

echo $html;
?> 